### ISSUE TITLE
Not work on some video. [update]

### ISSUE THREAD

**Issue by zhainanjp** [inbasic/iaextractor#75] opened 2015-02-12 06:45 UTC
Yes, i'm logged-in and can play the video on the built-in player after one click.
But still cannt download, even the video is playing.

----------------

" inbasic commented 3 days ago
You need to be logged-in and make sure you are able to play the video on the built-in player. If so you would be able to download as well."

----------------

Not work on some video.
Such as: youtube id hM249sR6xBM

**Comment by inbasic** [comment] 2016-04-03 14:55
This is duplicate of https://github.com/inbasic/iaextractor/issues/104
Can you try the latest  built
https://github.com/inbasic/iaextractor/blob/beta/builds/feca4b87-3be4-43da-a1b1-137c24220968@jetpack-0.5.0b4.xpi?raw=true

**Closed by inbasic** 2016-04-03 14:55 UTC
