### ISSUE TITLE
Not detecting AAC 256 or OPUS 160 streams in videos uploaded after May 29th.

### ISSUE THREAD

**Issue by augur42** [inbasic/iaextractor#89] opened 2015-06-13 00:00 UTC
version 0.4.4.1.1-signed
Firefox 38.0.5

I am virtually certain it is NOT a bug, but something changed.
Videos in the same channel, uploaded by the same person, are no longer showing or downloading the highest bitrate audio streams.

I want the 1080p stream so it has to be dash, but that means the highest audio is AAC 128 whilst the MP4 720p has AAC 192 built in.

I am wondering if maybe youtube changed something on May 30th or if they decided to stop creating the higher streams since according to wikipedia the AAC 256 is not actually used during playback.

example videos
Channel #music
https://www.youtube.com/channel/UC-9-kyTW8ZkZNDHQJ6FgpwQ

Taylor Swift - Bad Blood ft. Kendrick Lamar
Published 17th May 2015
https://www.youtube.com/watch?v=QcIy9NiNbmo

Prince Royce - Back It Up (Official Video) ft. Jennifer Lopez, Pitbull
Published 9th June 2015
https://www.youtube.com/watch?v=9w9dXWU5nMI

egame streamer Drift0r
Published 29th May 2015
https://www.youtube.com/watch?v=pALpffLMBNw
Published 30th May 2015
https://www.youtube.com/watch?v=h3W4gNyXceE

**Comment by Metaphorce812** [comment] 2015-07-19 21:51
I don't know why (maybe just to piss people off?), but YouTube has stopped providing AAC 256kbps CBR DASH streams (scroll down and notice that iTag 141 has been discontinued):
https://en.wikipedia.org/wiki/YouTube#Quality_and_formats

This means that the highest quality AAC DASH audio is 128kbps CBR, which sucks. However 720p combined video+audio streams contain ~192kbps VBR AAC which is now the highest quality audio available anywhere on YouTube.
Would it be possible to extract that audio stream from the 720p video and combine it with the 1080p DASH video to get the highest quality video/audio in one file?

**Comment by augur42** [comment] 2015-07-20 00:10
Thanks for the link, I checked the wikipedia page weeks ago and iTag 141 was still listed. Checking the history it was edited to change the iTag 141 part at 12:43, 17 July 2015 which is 2.5 days ago.
I did notice at one point around my first post that YTVAAD started downloading the 720p192aac for the audio stream to combine with the 1080p mp4 dash stream as it was the highest quality audio stream present, but that was fixed pretty quickly and now the check for 256aac has been completely removed, even if it is present for older videos on youtubes servers.

I'm guessing they did it to save the computer time and costs with encoding another audio stream, if it wasn't used for streaming purposes it wasn't really being used. We were just lucky to have had it at all. I do consider it odd that the highest quality video doesn't also have the highest quality audio, maybe they'll redress that at some point in the future, unfortunately it will probably be by reducing the 720p192aac to 720p128aac.

There is no reason why you couldn't download both the 720p192aac and 1080p dash and then mux the 192aac into the 1080p dash, just use ffmpeg.
In fact I just tried downloading the 1080p dash with automatic 128aac and the 720p192aac versions of a video, dragged them both into the Media Converter and Muxer (The split off Conversion Tools) and it output a 1080p192aac file. NB the audio stream muxed into the output is determined by the order the two files are selected for dropping into the window. I had to select the file with the audio stream I wanted first i.e. the 720p192aac then the 1080p128aac. It didn't matter the order for the video, no matter which I picked first the output was always 1080p.

**Comment by Metaphorce812** [comment] 2015-07-20 22:17
Yeah I've used mkvmergeGUI to combine them in the past the way you described. I just wish that YTVAAD would do it automatically now that YouTube has screwed up the audio. If you're downloading a lot of music videos it's a hassle to download them both in 720p & 1080p then individually remux each one. I also find it weird that the 720p audio stream is variable bitrate while all the other available audio streams are constant bitrate. If they want to reduce file sizes they should be using VBR.

**Comment by inbasic** [comment] 2016-04-03 14:47
Duplicate of https://github.com/inbasic/iaextractor/issues/121

**Closed by inbasic** 2016-04-03 14:47 UTC
