### ISSUE TITLE
Need to refresh page to see Download button.

### ISSUE THREAD

**Issue by SlimF** [inbasic/iaextractor#92] opened 2015-06-20 21:12 UTC
Since 1 or 2 days ago I noticed that every time I start a new video, the Download button is missing until I refresh the page. I'm using latest FF version on Windows 10, I tried to reinstall the addon and tried with a new profile too but no luck. A friend has the same problem on W7 too.

**Comment by inbasic** [comment] 2015-06-21 05:33
Please try the addon on a clean profile, https://support.mozilla.org/en-US/kb/profile-manager-create-and-remove-firefox-profiles

**Comment by SlimF** [comment] 2015-06-21 09:22
I tried with a new profile but the problem persists. :/

**Comment by inbasic** [comment] 2015-06-21 14:30
okay, please open the Error Console (Ctrl + Shift + J), clear it and open a YouTube page. Is there any new relevant error in the console?

**Comment by SlimF** [comment] 2015-06-22 09:30
http://pastebin.com/J55DeH2r and after a refresh http://pastebin.com/GiYjZ4st

**Comment by jdgalt** [comment] 2015-06-23 01:42
I see this problem too.

**Comment by lsimpson50** [comment] 2015-06-23 17:53
This problem just started for me too.  Firefox 38.0.5, Windows 7.

**Comment by Nilknarf2015** [comment] 2015-06-26 05:19
This same issue just started for me right after updating to Firefox 38.0.5. I made sure I have the latest version of the addon. I'm on Win 7 64 bit.

**Comment by tedparkes** [comment] 2015-07-10 14:59
Same issue, Firefox 38.0.5, dont even see the top right download button, nevermind one on the page, it looks like the addon is not installed at all.

**Comment by tedparkes** [comment] 2015-07-10 15:35
Updating to Firefox 39 has resolved the issue.

**Comment by lsimpson50** [comment] 2015-07-10 18:01
Updating to Firefox 39 did not solve the issue for me.  The problem is the same with 39.

**Comment by 98se** [comment] 2015-07-14 21:42
When Greasemonkey is installed, it was settled.
I don't understand the reason, but you'd be able to bypass this issue.

**Comment by inbasic** [comment] 2015-07-16 13:00
The issue is fixed on the latest built,
https://addons.mozilla.org/en-US/firefox/addon/youtube-video-and-audio-dow/versions/0.4.5

Thanks for the report.

**Closed by inbasic** 2015-07-16 13:00 UTC
